
# Copy from build env
COPY . /
RUN /bin/bash -c 'shopt -s dotglob \
 && chmod +x /entrypoint.sh \
 && chmod +x /entrypoint.d/* \
 && chmod +x /entrypoint.db.d/* \
 && shopt -u dotglob'

# Create app user & folders
RUN addgroup --system --gid ${APP_UID} odoo; \
    adduser --system --uid ${APP_GID} --ingroup odoo --home /opt/odoo --disabled-login --shell /sbin/nologin odoo; \
    mkdir -p "${ODOO_PRST_DIR}"; \
    chown -R odoo:odoo "${ODOO_PRST_DIR}"; \
    rm /var/log/faillog var/log/lastlog;

# Fix locale                 //-- for some tests that depend on locale (babel python-lib)
# Size: ca. 3.6MB
RUN sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && \
    dpkg-reconfigure --frontend=noninteractive locales && \
    update-locale LANG=en_US.UTF-8
ENV LANG=en_US.UTF-8 \
    LANGUAGE=en_US:en \
    LC_ALL=en_US.UTF-8

ENTRYPOINT ["/entrypoint.sh"]
VOLUME ["${ODOO_PRST_DIR}"]

USER odoo

# Grab newer werkzeug        //-- for right IP in logs https://git.io/fNu6v
# Size: ca. 1.9MB
RUN pip --quiet --quiet install --no-cache-dir --user Werkzeug==0.14.1; \
    find /usr/local -depth \
        \( \
            \( -type d -a \( -name test -o -name tests \) \) \
            -o \
            \( -type f -a \( -name '*.pyc' -o -name '*.pyo' \) \) \
        \) -exec rm -rf '{}' +;
